#!/bin/sh

# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT
# set -x

# SOURCE_DIST is the path to unzipped stock recovery update package of jellybean 
SOURCE_DIST=~/dev/android/n2/update

VENDOR=cellon
DEVICE=c8690

VENDOR_DIR=../../../vendor/$VENDOR/$DEVICE

PROPRIETARY_DIR=$VENDOR_DIR/proprietary

if [ -d $PROPRIETARY_DIR/$DIR ] ; then
  rm -rf $PROPRIETARY_DIR/$DIR
fi
mkdir -p $PROPRIETARY_DIR



echo "Pulling proprietary files..."
for FILE in `cat proprietary-files.txt | grep -v ^# | grep -v ^$`; do
    OUT_FILE=
    DIR=`dirname $FILE`
    
    if [ ! -d $PROPRIETARY_DIR/$DIR ]; then
        echo "mkdir -p $PROPRIETARY_DIR/$DIR"
    fi
    #echo $SOURCE_DIST/$FILE $PROPRIETARY_DIR/$FILE
    echo "cp -fr $SOURCE_DIST/$FILE $PROPRIETARY_DIR/$FILE"
done
